version: '3.8'

services:
  database:
    container_name: database
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: symfony
      POSTGRES_DB: symfony_docker
    healthcheck:
      test: pg_isready -U symfony -d symfony_docker
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  php:
    container_name: php
    build:
      context: .
    ports:
      - "80:80"
    depends_on:
      database:
        condition: service_healthy
