version: '3.8'

services:
  database:
    container_name: database
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  php:
    container_name: php
    build:
      context: .
    ports:
      - "80:80"
    depends_on:
      database:
        condition: service_healthy
